spring.application.name=mediflow-backend

# PostgreSQL - Hardcoded for Render
spring.datasource.url=jdbc:postgresql://dpg-d7cthr67r5hc739q9ir0-a.oregon-postgres.render.com/mediflow_dpnq
spring.datasource.username=mediflow_dpnq_user
spring.datasource.password=okOKw4WwBGzrKJyqdi3hOmHjCn5TjD5V
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
mediflow.jwt.secret=MediFlowSuperSecretKeyThatIsAtLeast256BitsLong2024!@#
mediflow.jwt.expiration=86400000

# Server
server.port=${PORT:8081}